name: Kubernetes Dist Train Integration Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  kubernetes-launch:
    runs-on: ubuntu-18.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout TorchX
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2
        continue-on-error: true
      - name: Configure Kube Config
        run: |
          set -eux
          if [ -n "$AWS_SESSION_TOKEN" ]; then
            aws eks update-kubeconfig --region=us-west-2 --name=${{ secrets.EKS_CLUSTER_NAME }}
          fi
      - name: Configure Docker
        run: |
          set -eux
          if [ -n "$AWS_SESSION_TOKEN" ]; then
            aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 495572122715.dkr.ecr.us-west-2.amazonaws.com
          fi
      - name: Install dependencies
        run: |
          set -eux
          pip install -e .[kubernetes]
      - name: Run Kubernetes Integration Tests
        env:
          INTEGRATION_TEST_STORAGE: ${{ secrets.INTEGRATION_TEST_STORAGE }}
          CONTAINER_REPO: ${{ secrets.CONTAINER_REPO }}
        run: |
          if [ -z "$AWS_SESSION_TOKEN" ]; then
            # only dryrun if no secrets
            ARGS="--dryrun"
          else
            ARGS=
          fi
          scripts/kube_dist_trainer.py $ARGS
